<?php

declare(strict_types=1);

namespace App\Seed;

use App\Model\User;
use Illuminate\Database\DatabaseManager;
use Symfony\Component\String\ByteString;
use WouterJ\EloquentBundle\Seeder;

final class UserSeeder extends Seeder
{
    public function __construct(
        private DatabaseManager $db,
    ) {
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $userTable = $this->db->table(User::TABLE);
        for ($i = 0; $i < 10; ++$i) {
            $userTable->insert([
                [
                    // 'id' => 1, id is autogenerated
                    'email' => \sprintf('user%d@example.com', $i),
                    'password' => password_hash(ByteString::fromRandom(32)->toString(), \PASSWORD_DEFAULT),
                    'pseudo' => 'User '.$i,
                    'created_at' => time(),
                    'updated_at' => time(),
                ],
            ]);
        }
    }
}
